### ISSUE TITLE
what version of emi need to correct work with Psychedelicraft?

### ISSUE THREAD

**Issue by alexthermite546** [Sollace/Psychedelicraft#58]
^

**Comment by alexthermite546** [comment]
because if I use the latest version of EMI, then a critical error appears

**Comment by MimzyFang** [comment]
> because if I use the latest version of EMI, then a critical error appears

install the latest version of TLA https://modrinth.com/mod/tla-api/version/1.2.1+mc.1.21

**Comment by alexthermite546** [comment]
> > because if I use the latest version of EMI, then a critical error appears
> 
> install the latest version of TLA https://modrinth.com/mod/tla-api/version/1.2.1+mc.1.21

It didn't help

**Comment by alexthermite546** [comment]
```
[19:52:15] [Thread-44/ERROR]: [EMI] Critical error occured during reload:
[19:52:15] [Thread-44/INFO]: [STDERR]: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2960.equals(Object)" because the return value of "dev.emi.emi.api.recipe.EmiRecipe.getId()" is null
[19:52:15] [Thread-44/INFO]: [STDERR]: 	at ivorius.psychedelicraft.compat.emi.RecipeUtil.lambda$replaceRecipe$0(RecipeUtil.java:49)
[19:52:15] [Thread-44/INFO]: [STDERR]: 	at dev.emi.emi.registry.EmiRecipes.lambda$bake$3(EmiRecipes.java:85)
[19:52:15] [Thread-44/INFO]: [STDERR]: 	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178)
[19:52:15] [Thread-44/INFO]: [STDERR]: 	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
[19:52:15] [Thread-44/INFO]: [STDERR]: 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
[19:52:15] [Thread-44/INFO]: [STDERR]: 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
[19:52:15] [Thread-44/INFO]: [STDERR]: 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
[19:52:15] [Thread-44/INFO]: [STDERR]: 	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
[19:52:15] [Thread-44/INFO]: [STDERR]: 	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
[19:52:15] [Thread-44/INFO]: [STDERR]: 	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622)
[19:52:15] [Thread-44/INFO]: [STDERR]: 	at java.base/java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627)
[19:52:15] [Thread-44/INFO]: [STDERR]: 	at dev.emi.emi.registry.EmiRecipes.bake(EmiRecipes.java:90)
[19:52:15] [Thread-44/INFO]: [STDERR]: 	at dev.emi.emi.runtime.EmiReloadManager$ReloadWorker.run(EmiReloadManager.java:218)
[19:52:15] [Thread-44/INFO]: [STDERR]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[19:52:15] [Thread-44/ERROR]: [EMI] java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2960.equals(Object)" because the return value of "dev.emi.emi.api.recipe.EmiRecipe.getId()" is null
	at ivorius.psychedelicraft.compat.emi.RecipeUtil.lambda$replaceRecipe$0(RecipeUtil.java:49)
	at dev.emi.emi.registry.EmiRecipes.lambda$bake$3(EmiRecipes.java:85)
	at java.base
[19:52:15] [Thread-44/ERROR]: [EMI] java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178)
	at java.base
[19:52:15] [Thread-44/ERROR]: [EMI] java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base
[19:52:15] [Thread-44/ERROR]: [EMI] java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base
[19:52:15] [Thread-44/ERROR]: [EMI] java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base
[19:52:15] [Thread-44/ERROR]: [EMI] java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
	at java.base
[19:52:15] [Thread-44/ERROR]: [EMI] java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.base
[19:52:15] [Thread-44/ERROR]: [EMI] java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
	at java.base
[19:52:15] [Thread-44/ERROR]: [EMI] java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622)
	at java.base
[19:52:15] [Thread-44/ERROR]: [EMI] java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627)
	at dev.emi.emi.registry.EmiRecipes.bake(EmiRecipes.java:90)
	at dev.emi.emi.runtime.EmiReloadManager$ReloadWorker.run(EmiReloadManager.java:218)
	at java.base
[19:52:15] [Thread-44/ERROR]: [EMI] java.lang.Thread.run(Thread.java:833)

[19:52:15] [Thread-44/INFO]: [EMI] Starting EMI reload...
```

**Comment by alexthermite546** [comment]
minecraft 1.20.1

**Comment by Sollace** [comment]
The error you're showing is a bug with EMI. We can't do anything about that.
